[package]
authors = ["Gestalt LUR <gestapolur@gmail.com>"]
name = "ali-ecs-ctl"
version = "0.2.0"

[dependencies]
chrono = "0.3"
clap = "~2.22.2"
hyper = "0.10"
reqwest = "0.5.0"
rustc-serialize = "0.3"
sha1 = "0.2.0"
url = "1.4.0"

[dependencies.uuid]
features = ["serde", "v4"]
version = "0.4"
