[package]
authors = ["Gestalt LUR <gestapolur@gmail.com>"]
name = "ali-ecs-ctl"
version = "0.4.0"

[dependencies]
base64 = "0.4"
chrono = "0.3"
clap = "2.22"
hyper = "0.10"
reqwest = "0.5"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
sha1 = "0.2"
url = "1.4"

[dependencies.uuid]
features = ["v4"]
version = "0.4"

[dev-dependencies]
hex = "0.2"

[features]
unstable = []
