[package]
authors = ["Gestalt LUR <gestapolur@gmail.com>"]
name = "ali-ecs-ctl"
version = "0.4.0"

[dependencies]
base64 = "0.4"
chrono = "0.3"
clap = "2.22"
hmac-sha1 = "0.1"
hyper = "0.10"
reqwest = "0.5"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
url = "1.4"

[dependencies.uuid]
features = ["v4"]
version = "0.4"

[features]
unstable = []
