[package]
authors = ["Gestalt LUR <gestapolur@gmail.com>"]
name = "ali-ecs-ctl"
version = "1.0.0"

[dependencies]
base64 = "0.4"
chrono = "0.3"
clap = "2.22"
hmac-sha1 = "0.1"
hyper = "0.10"
num_cpus = "1.3"
reqwest = "0.5"
scoped-pool = "1.0"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
url = "1.4"
prettytable-rs = "0.6"
statsd = "0.7.0"

[dependencies.uuid]
features = ["v4"]
version = "0.4"

[features]
unstable = []
